### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yosefy** [brunopsoares/prometheus_couchbase_exporter#1]
hi, i got this error 
text format parsing error in line 28: invalid metric name in comment

abouth this line:
# HELP couchbase_bucket_stats_ep_dcp_views+2i_total_backlog_size ep_dcp_views+2i_total_backlog_size

**Comment by brunopsoares** [comment]
Hi,
Can you please check if this PR can resolve this issue: https://github.com/brunopsoares/prometheus_couchbase_exporter/pull/2?

Thanks and sorry for this delay...

**Comment by yosefy** [comment]
ah you are alive :) !

for me it fixed the issue

thanks for merging
