### ISSUE TITLE
is this still being maintained?

### ISSUE THREAD

**Issue by caarlos0** [brunopsoares/prometheus_couchbase_exporter#11]
is this project still being maintained?

I'm asking because I kind of use it so if it's not being maintained anymore I'll fork it or do something else.. hehe

Thanks for the project, btw :)

**Comment by danielmrosa** [comment]
Hi @brunopsoares 
Congrats for this project!. I would like to know if you have some grafana template ready for this project or can you recommend one ?
Thanks.

**Comment by amithrh** [comment]
Please let me know which metric tells me the cluster health ?

**Comment by caarlos0** [comment]
FWIW, we've written this: https://github.com/totvslabs/couchbase-exporter

**Comment by danielmotaleite** [comment]
Couchbase have now their own official exporter: 
https://github.com/couchbase/couchbase-exporter
