### ISSUE TITLE
buckets problem

### ISSUE THREAD

**Issue by yosefy** [brunopsoares/prometheus_couchbase_exporter#3]
the exporter itterates all buckets but adds only metrics from the last one

tried to find a way to fix it but i couldn't

thanks

**Comment by HugoLafleur** [comment]
paschdan's fix worked for me; strongly suggest to merge, build and push to pypi

Cheers!

**Comment by brunopsoares** [comment]
Sorry for this (big) delay and thanks for your improvement!
